# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-st-odyssey"
BBFILE_PATTERN_meta-st-odyssey = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-st-odyssey = "7"

LAYERDEPENDS_meta-st-odyssey = "core"
LAYERSERIES_COMPAT_meta-st-odyssey = "mickledore"

STM32MP_DT_FILES_EMMC += "stm32mp157c-odyssey"
STM32MP_DT_FILES_SDCARD += "stm32mp157c-odyssey"
UBOOT_EXTLINUX_TARGETS_EXTRA_CONFIG[stm32mp157c-odyssey] += "stm32mp157c-odyssey"

BOOTDEVICE_LABELS = "emmc sdcard"
